// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Br: typeof import('vue-termui')['TuiNewline']
    Deps: typeof import('./src/components/Deps.vue')['default']
    Div: typeof import('vue-termui')['TuiBox']
    Download: typeof import('./src/components/Download.vue')['default']
    Guide: typeof import('./src/components/Guide.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    Link: typeof import('vue-termui')['TuiLink']
    Package: typeof import('./src/components/Package.vue')['default']
    Progressbar: typeof import('vue-termui')['TuiProgressBar']
    Span: typeof import('vue-termui')['TuiText']
  }
}
