// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Deps: typeof import('./src/components/Search/Deps.vue')['default']
    Div: typeof import('vue-termui')['TuiBox']
    Download: typeof import('./src/components/Search/Download.vue')['default']
    Guide: typeof import('./src/components/Search/Guide.vue')['default']
    Header: typeof import('./src/components/Search/Header.vue')['default']
    InputBox: typeof import('./src/components/Search/InputBox.vue')['default']
    Package: typeof import('./src/components/Search/Package.vue')['default']
    Span: typeof import('vue-termui')['TuiText']
  }
}
